-- Trade tags: auto-generated by V3 on every closed trade
create table if not exists trade_tags (
  id                  uuid primary key default gen_random_uuid(),
  order_ticket        text,
  symbol              text not null,
  close_time          text not null,
  setup_type          text,   -- breakout, pullback, reversal, vwap, scalp, range, other
  session_phase       text,   -- open, midday, close
  market_regime       text,   -- trending, ranging, volatile, unknown
  planned_vs_impulse  text,   -- planned, impulse, unknown
  tagged_at           timestamptz not null default now(),
  unique(symbol, close_time)
);

create index if not exists trade_tags_symbol_idx     on trade_tags(symbol);
create index if not exists trade_tags_setup_idx      on trade_tags(setup_type);
create index if not exists trade_tags_close_time_idx on trade_tags(close_time desc);
